# ==============================================================================
# Program: multi_matrix_out.R
# Translated from: multi_out_3_02_EG.sas
# Date: Translated February 2026, checked for accuracy by Kerry Flaherty-Walia
# Function: Takes datasets generated by multi_comb program and produces 
#   pseudospecies arranged in columns by reference, gear, year, month, and date
#   for multivariate analysis (PRIMER, Canoco, etc.)
# ==============================================================================

library(tidyverse)
library(readr)
library(here)


# SETUP PARAMETERS - All modifications occur here===============================

# Number of estuary-specific datasets to pull from
estnum <- 1

# Estuary codes (2-character FIM program codes)
b1 <- "tb"
b2 <- ""
b3 <- ""
b4 <- ""
b5 <- ""
b6 <- ""

# Sampling type (1-character FIM program code), "_" for all sampling types
t <- "_"

# Filename suffix - to identify subset of data pulled (example: all, zone, gr, baysegment)
s <- "all"

# Standard prefix for output file names, example tb_20 (bay = tb, gr = 20)
r <- "tb_all"

# Treat Man Eme Ter Str as boolean (b) or ratio (r)
sanal <- "r"

# Treat Non Sav Alg as boolean (b) or ratio (r)
vanal <- "r"

# File paths - folder in project
path <- "Output"

# Size class option (0, 1, 2, or 3)
# 0: no size classes
# 1: <31, 31-50, 51-100, >100
# 2: 10mm sizes 1-39, 20mm 40-99, 50mm 100-399, 100mm 400-999, 1000mm >=1000
# 3: 20mm <100, 50mm 100-299, 100mm 300-999, 1000mm >=1000
sz_opt <- 0

# Gear filter values or # for all
#gear_values <- c('019','020')

# Zone filter values or unique(Zone) for all
#zone_values <- unique(Zone)

# Year filter values
year_values <- c(1996:2024)

# Month filter values
month_values <- c(1:12)

# Taxa to lump as single size class (no size differentiation)
no_sz <- c("9999999999")  # Use impossible species if none

# Selected species only?
sel_tag <- 0  # 1 = yes, 0 = no

# Retain zero catches? (given count of 1 instead of 0)
ret_zero <- "yes"  # "yes" or "no"

# Environmental variables to retain
env_var <- c("StartDepth", "slope", "temperature", "salinity", "dissolvedo2", 
            "bycatchquantity", "BottomVegCover", 
            "HA", "TH", "RU", "Non", "Alg", "Oth", "SAV")

# Factor variables to retain
fac_var <- c("z", "gr", "shore", "bveg", "bottom", "month", "season", "year", 
            "bay_zone_yr_season", "bay_zone_season", 
            "bay_zone_yr", "DominantVeg", "BvegCovBin")

# ==============================================================================
# READ DATA
# ==============================================================================

# Read combined data files
load(paste0(here(path, paste0(tolower(b1), tolower(t), s, "_c.RData")))) 
load(paste0(here(path, paste0(tolower(b1), tolower(t), s, "_l.RData"))))
len<-len_final%>%
  rename(species = NODCCODE)

# ==============================================================================
# PROCESS COMBINED DATA
# ==============================================================================

# Set Non to 1 if all vegetation is 0
com <- com %>%
  mutate(
    Non = ifelse(Non == 0 & SAV == 0 & Alg == 0 & HA == 0 & TH == 0 & RU == 0, 1, 0)
  )

# Convert to boolean if specified
if (toupper(sanal) == "B") {
  com <- com %>%
    mutate(
      Man = ifelse(Man > 0, 1, 0),
      Eme = ifelse(Eme > 0, 1, 0),
      Ter = ifelse(Ter > 0, 1, 0),
      Str = ifelse(Str > 0, 1, 0)
    )
}

if (toupper(vanal) == "B") {
  com <- com %>%
    mutate(
      Non = ifelse(Non > 0, 1, 0),
      SAV = ifelse(SAV > 0, 1, 0),
      Alg = ifelse(Alg > 0, 1, 0)
    )
}

# Apply filters
com <- com %>%
  filter(gr %in% gear_values) %>%
  filter(zone %in% zone_values) %>%
  filter(year %in% year_values) %>%
  filter(month(date) %in% month_values) %>%

# Sort and merge
com <- com %>% arrange(Reference, species)
len <- len %>% arrange(Reference, species)

one <- com %>%
  left_join(len, by = c("Reference","species")) %>%
  mutate(
    nodccode = species,
    count = replace_na(count, 1),
    nl = replace_na(nl, 1)
  )

# Handle zero catches
if (toupper(ret_zero) == "YES") {
  one <- one %>%
    mutate(number = ifelse(nodccode == '9998000000', 1, number))
} else {
  one <- one %>%
    mutate(number = ifelse(nodccode == '9998000000', 0, number))
}

# Delete unidentified specimens
one <- one %>% filter(species != '9999000000')

# Delete records with missing data
one <- one %>% filter(!is.na(nl), !is.na(count), number != 0)

# Assign counts where missing
one <- one %>%
  mutate(
    count = ifelse(count <= 0, 1, count),
    nl = ifelse(nl <= 0, 1, nl)
  )

# Group at genus level for small specimens
one <- one %>%
  mutate(
    genus = str_sub(species, 1, 8),
    species = case_when(
      # Argopecten
      genus %in% c('55090512') ~ paste0(str_sub(species, 1, 8), "00"),
      # Strongylura marina and timucu
      species %in% c('8803020201', '8803020203') & sl < 100 ~ paste0(str_sub(species, 1, 8), "00"),
      # Hyporhamphus
      genus == '880300102' & sl < 100 ~ paste0(str_sub(species, 1, 8), "00"),
      # Lepomis
      genus == '88351605' & sl < 20 ~ paste0(str_sub(species, 1, 8), "00"),
      # Eucinostomus
      genus == '88353901' & sl < 40 ~ paste0(str_sub(species, 1, 8), "00"),
      # Tilapia group
      genus %in% c('88356104', '88356114', '88356148') & sl < 40 ~ '8835615000',
      # Gobiosoma
      species %in% c('8847010603', '8847010601') & sl < 20 ~ paste0(str_sub(species, 1, 8), "00"),
      TRUE ~ species
    )
  )

# Remove size class on designated animals
one <- one %>%
  mutate(
    sl = ifelse(species %in% no_sz, 0, sl),
    count = ifelse(species %in% no_sz, 1, count),
    nl = ifelse(species %in% no_sz, 1, nl)
  )

# Calculate number per size class
one <- one %>%
  mutate(num = count/nl * number) %>%
  arrange(species)

# ==============================================================================
# GET SCIENTIFIC NAMES
# ==============================================================================

species_codes <- read_csv(paste0(s, "species_codes.csv"), show_col_types = FALSE)

two <- species_codes %>%
  mutate(
    species = as.character(nodccode),
    spp_cde = spp_code,
    # Remove periods and spaces from species codes
    spp_cde = str_replace_all(spp_cde, "\\.$", ""),
    spp_cde = str_replace_all(spp_cde, "\\. ", "_"),
    spp_cde = str_replace_all(spp_cde, " ", "_"),
    spp_cde = str_replace_all(spp_cde, "__", "_"),
    spp_code = spp_cde
  ) %>%
  select(species, spp_code, ScientificName) %>%
  arrange(species)

three <- one %>%
  left_join(two, by = "species")

# ==============================================================================
# ASSIGN SIZE CLASSES
# ==============================================================================

if (sz_opt == 0) {
  # Option 0: No size classes
  four <- three %>%
    mutate(
      pseudo = spp_code,
      SizeClass = "> 0mm"
    )
  
} else if (sz_opt == 1) {
  # Option 1: <31, 31-50, 51-100, >100
  four <- three %>%
    mutate(
      pseudo = case_when(
        sl < 1 ~ paste0(spp_code, "_0"),
        sl >= 1 & sl < 30 ~ paste0(spp_code, "_1"),
        sl >= 30 & sl < 50 ~ paste0(spp_code, "_2"),
        sl >= 50 & sl < 100 ~ paste0(spp_code, "_3"),
        sl >= 100 ~ paste0(spp_code, "_4"),
        TRUE ~ spp_code
      ),
      sz = str_sub(pseudo, -1, -1),
      SizeClass = case_when(
        sz == "1" ~ "0 to 30mm",
        sz == "2" ~ "31 to 50mm",
        sz == "3" ~ "51 to 100mm",
        sz == "4" ~ ">100mm",
        TRUE ~ "> 0mm"
      )
    ) %>%
    select(-sz)
  
} else if (sz_opt == 2) {
  # Option 2: 10mm sizes 1-39, 20mm 40-99, 50mm 100-399, 100mm 400-999, 1000mm >=1000
  four <- three %>%
    mutate(
      sl = case_when(
        sl < 1 ~ 0,
        sl < 40 ~ floor(sl/10)*10 + 5,
        sl < 100 ~ floor(sl/20)*20 + 10,
        sl < 400 ~ floor(sl/50)*50 + 25,
        sl < 1000 ~ floor(sl/100)*100 + 50,
        sl >= 1000 ~ floor(sl/1000)*1000 + 500,
        TRUE ~ sl
      ),
      pseudo = case_when(
        sl < 10 ~ paste0(spp_code, "_000", sl),
        sl < 100 ~ paste0(spp_code, "_00", sl),
        sl < 1000 ~ paste0(spp_code, "_0", sl),
        sl >= 1000 ~ paste0(spp_code, "_", sl),
        TRUE ~ spp_code
      ),
      SizeClass = case_when(
        sl < 40 ~ paste0(sl-5, " to ", sl+4),
        sl < 100 ~ paste0(sl-10, " to ", sl+9),
        sl < 400 ~ paste0(sl-25, " to ", sl+24),
        sl < 1000 ~ paste0(sl-50, " to ", sl+49),
        sl >= 1000 ~ paste0(sl-500, " to ", sl+499),
        TRUE ~ "> 0mm"
      )
    )
  
} else if (sz_opt == 3) {
  # Option 3: 20mm <100, 50mm 100-299, 100mm 300-999, 1000mm >=1000
  four <- three %>%
    mutate(
      sl = case_when(
        sl < 1 ~ 0,
        sl < 100 ~ floor(sl/20)*20 + 10,
        sl < 300 ~ floor(sl/50)*50 + 25,
        sl < 1000 ~ floor(sl/100)*100 + 50,
        sl >= 1000 ~ floor(sl/1000)*1000 + 500,
        TRUE ~ sl
      ),
      pseudo = case_when(
        sl < 10 ~ paste0(spp_code, "_000", sl),
        sl < 100 ~ paste0(spp_code, "_00", sl),
        sl < 1000 ~ paste0(spp_code, "_0", sl),
        sl >= 1000 ~ paste0(spp_code, "_", sl),
        TRUE ~ spp_code
      ),
      SizeClass = case_when(
        sl < 100 ~ paste0(sl-10, " to ", sl+10),
        sl < 300 ~ paste0(sl-25, " to ", sl+24),
        sl < 1000 ~ paste0(sl-50, " to ", sl+49),
        sl >= 1000 ~ paste0(sl-500, " to ", sl+499),
        TRUE ~ "> 0mm"
      )
    )
  
} else {
  # Default to option 0
  four <- three %>%
    mutate(
      pseudo = spp_code,
      SizeClass = "> 0mm"
    )
}

four <- four %>% arrange(reference, pseudo)

# ==============================================================================
# COUNT ANIMALS AND CALCULATE DENSITY
# ==============================================================================

# Count animals per pseudospecies
five <- four %>%
  group_by(reference, pseudo) %>%
  summarize(n = sum(num, na.rm = TRUE), .groups = 'drop') %>%
  left_join(
    four %>% select(-num) %>% distinct(),
    by = c("reference", "pseudo")
  )

# Calculate density/CPUE
six <- five %>%
  mutate(
    density = ifelse(gr != 300, n, n/effort * 7.2)  # Standardize trawls to 720 sq m
  ) %>%
  arrange(reference, pseudo)

# Check for missing densities
six_check <- six %>%
  filter(is.na(density) | density == 0)

if (nrow(six_check) > 0) {
  cat("\nWarning: Some records have no density values:\n")
  print(six_check %>% select(reference, bio_reference, nodccode, pseudo, density))
}

# ==============================================================================
# TRANSPOSE TO GET PSEUDOSPECIES AS COLUMNS
# ==============================================================================

seven <- six %>%
  select(reference, pseudo, density) %>%
  pivot_wider(names_from = pseudo, values_from = density, values_fill = 0)

# ==============================================================================
# PROCESS ENVIRONMENTAL DATA
# ==============================================================================

eleven <- one %>%
  distinct(reference, .keep_all = TRUE) %>%
  mutate(
    bay_zone_yr = paste0(z, "_", year),
    season = case_when(
      month %in% c(4, 6) ~ "Dry",
      month %in% c(8, 10) ~ "Wet",
      TRUE ~ NA_character_
    ),
    bay_zone_yr_season = paste0(bay_zone_yr, "_", season),
    bay_zone_season = paste0(z, "_", season),
    BvegCovBin = case_when(
      BottomVegCover > 75 ~ "76-100",
      BottomVegCover < 26 ~ "0-25",
      BottomVegCover > 25 & BottomVegCover <= 50 ~ "26-50",
      BottomVegCover > 50 & BottomVegCover <= 75 ~ "51-75",
      BottomVegCover %in% c('.', '101') ~ "Unk",
      TRUE ~ "Unk"
    )
  )

# ==============================================================================
# MERGE AND CREATE OUTPUT DATASETS
# ==============================================================================

twelve <- seven %>%
  left_join(eleven, by = "reference")

# Create output datasets
catch_data <- twelve %>%
  select(-all_of(env_var), -all_of(fac_var))

env_numeric <- twelve %>%
  select(reference, all_of(env_var))

env_character <- twelve %>%
  select(reference, all_of(fac_var))

species_data <- four %>%
  distinct(pseudo, .keep_all = TRUE) %>%
  select(nodccode, ScientificName, pseudo, spp_code, SizeClass) %>%
  arrange(pseudo)

# ==============================================================================
# WRITE OUTPUT FILES
# ==============================================================================

output_path <- path
prefix <- r

# Write CSV files
write_csv(catch_data, paste0(output_path, prefix, "_catch.csv"))
write_csv(env_numeric, paste0(output_path, prefix, "_env_numeric.csv"))
write_csv(env_character, paste0(output_path, prefix, "_env_charcter.csv"))
write_csv(species_data, paste0(output_path, prefix, "_species.csv"))

cat("\nOutput files written:\n")
cat(paste0("  ", prefix, "_catch.csv\n"))
cat(paste0("  ", prefix, "_env_numeric.csv\n"))
cat(paste0("  ", prefix, "_env_charcter.csv\n"))
cat(paste0("  ", prefix, "_species.csv\n"))

cat("\nProcessing complete!\n")
